---
- hosts: all

  tasks:
  - name: Upgrade System
    become: yes
    apt:
      update_cache: yes
      upgrade: yes
  
  - name: Python Mysql
  # Ansible requires this to operate on DBs.
    become: yes
    apt:
      name: python-mysqldb

  - name: Install Nginx
    become: yes
    apt:
      name: nginx

  - name: Install Mysql
    become: yes
    apt:
      name: mysql-server

  - name: Install PHP
    become: yes
    apt:
      name: php5-fpm 

  - name: Install Some PHP Image Tools
    become: yes
    apt:
      name: php5-gd

  - name: Allow PHP Access to SSH Functionality
    become: yes
    apt:
      name: libssh2-php
  
  - name: Install PHP-Mysql
    become: yes
    apt:
      name: php5-mysql

  - name: Clean Up Nginx.conf  
    # Nginx's default plays poorly w/ VBox; causes overagressive caching.
    lineinfile:
      dest: /etc/nginx/nginx.conf
      regexp: 'sendfile'
      line: 'sendfile off;'

  - name: Address PHP
    become: yes
    template:
      src: provisioning/site_default.conf
      dest: /etc/nginx/sites-available/default

  - name: Restart Nginx
    # TODO: This should only run if nginx.conf has been changed in prev step.
    service:
      name: nginx
      state: restarted  

  # - name: Restart PHP
  #   service:
  #     name: php5-fpm
  #     state: restarted

  - name: Create WP Database
    become: yes
    mysql_db: 
      name: wordpress
      state: present

  - name: Create WP DB User
    become: yes
    mysql_user:
      name: wordpress
      password: wordpress
      priv: 'wordpress.*:ALL'
      state: present

  - name: Download WP Tarball
    get_url:
      url: https://wordpress.org/latest.tar.gz 
      dest: /tmp/wordpress.tar.gz

  